### ISSUE TITLE
How does DeepMosaic perform on PCR-amplified WES data?

### ISSUE THREAD

**Issue by sattarkh** [Virginiaxu/DeepMosaic#1]
DeepMosaic seems like a very powerful tool. I may have missed it, but it looks in the paper you have trained the model on PCR-amplified libraries and tested it on PCR-free libraries. How does DeepMoasic perform if tested on PCR-amplified libraries, specifically WES data?

**Comment by shishenyxx** [comment]
Dear Dr. Sattar,

Thank you for your interests in DeepMosaic, the software is trained with PCR-amplified WGS libraries and computationally simulated data and tested on other PCR-free or PCR amplified WGS libraries, because of the biased depth from exome capture, the current version and parameters are only optimized for genome data. We are currently testing DeepMosaic on PCR-amplified captured WES data, will release the recommended parameters and sensitivity measurement once we finish our internal testing!

Best,

Xiaoxu

**Comment by shishenyxx** [comment]
Hi Dr. Sattar,

Just an update that per our assessment, DeepMosaic (the current genome version) doubled the validation rate compared with our previous exome mosaic calling pipelines. While this is still only 40%. Given the high false-positive rates calling mosaic variants from WES, we think that's already providing a much more convincing alternative compared with other methods we have tried.

Best,

Xiaoxu

**Comment by sattarkh** [comment]
Hi Xiaoxu,

Thank you for the update. May I ask, what pipelines are you camping it to?
Also, is this in tumor-only or paired mode?

Thanks,
Sattar

**Comment by shishenyxx** [comment]
Hi Sattar,

1. We are comparing it with GATK Polidy 50 + filters (PMID 33781308)
2. Tumor only, the tested one was on Mutect2 single mode with an in-house panel of normal.

Best,

Xiaoxu

**Comment by sattarkh** [comment]
Perfect, thanks for that information. I am in the process of validating
some M2 variants and I may give DeepMosaic a try after I have a validated
callset.

Thanks again,
Sattar

**Comment by shishenyxx** [comment]
Hi Sattar,

Yeah please try and we welcome all feedback from you. You can feed DeepMosaic with the raw M2 output (maybe select "PASS" to increase the specificity) and we can see from there.

Best,

Xiaoxu

**Comment by sattarkh** [comment]
Will do, thanks.
