### ISSUE TITLE
DeepMosaic performance at 30x depth?

### ISSUE THREAD

**Issue by changhan1110** [Virginiaxu/DeepMosaic#5]
Hi.

My main question is **"Is it recommended to run DeepMosaic to identify MVs in 30x data?"**

I am planning to pass thousands of human genome data (bam, vcf) to DeepMosaic, but their depth is 30x mostly.
In the DeepMosaic paper, 30x results seem to be not okay from Extended Data Fig. 1.
<img width="687" alt="image" src="https://user-images.githubusercontent.com/44763914/210918358-e03ca604-ef67-4b42-81d4-8927c9fde5ab.png">

And there is no data in the Main Figure 2 and Extended Data Figure 5.
![image](https://user-images.githubusercontent.com/44763914/210918707-4d955ea1-916b-4507-8cd6-266d8552b39e.png)

It looks okay in Extended Data Fig. 1 but I am not sure because I have no experience on it.

Can I use DeepMosaic for 30x data?

I also am wondering about the runtime (cpu time, wall time...)

Thanks,
James

**Comment by shishenyxx** [comment]
> I am planning to pass thousands of human genome data (bam, vcf) to DeepMosaic, but their depth is 30x mostly.
> In the DeepMosaic paper, 30x results seem to be not okay from Extended Data Fig. 1.

Hi,

You can definitely use DeepMosaic for low-depth WGS, and that's one of the advantages of the caller.

Extended Data Figure 1 is only to showcase what it looks like for human eyes, the machine should be able to detect some variants with DeepMosaic, especially at higher allelic fractions. Low allelic fractions might vary case by case. I would suggest you calculate the average depth (has to be an integer though) for each sample and put it into the input file instead of just putting 30.

Depending on the number of vcfs and the performance of your node should be one to a dozen hours per genome per CPU (please find the benchmark in Extended Data Fig. 10). If you have GPU nodes and you configure them well could be faster. I would do a small-scale pilot and see how it goes before running your thousands of genomes.

Best,

Xiaoxu

**Comment by shishenyxx** [comment]
> Hi.
> 
> My main question is **"Is it recommended to run DeepMosaic to identify MVs in 30x data?"**
> 
> I am planning to pass thousands of human genome data (bam, vcf) to DeepMosaic, but their depth is 30x mostly. In the DeepMosaic paper, 30x results seem to be not okay from Extended Data Fig. 1. <img alt="image" width="687" src="https://user-images.githubusercontent.com/44763914/210918358-e03ca604-ef67-4b42-81d4-8927c9fde5ab.png">
> 
> And there is no data in the Main Figure 2 and Extended Data Figure 5. ![image](https://user-images.githubusercontent.com/44763914/210918707-4d955ea1-916b-4507-8cd6-266d8552b39e.png)
> 
> It looks okay in Extended Data Fig. 1 but I am not sure because I have no experience on it.
> 
> Can I use DeepMosaic for 30x data?
> 
> I also am wondering about the runtime (cpu time, wall time...)
> 
> Thanks, James

Hi James,

Sorry just saw that you edited your question. Compared with other methods we tried, I believe from our experience DeepMosaic is more suitable for mosaic variant calling in 30x WGS, especially if you don't have a matched control sample, as its training set already contains some 30x data. Although in general, it is challenging to detect mosaic variants from 30x WGS, we are testing some existing genomes in house: to make the long story short, if the genome quality is good, no contaminations, sequenced from DNA extracted from fresh frozen tissue, not FFPE, we get average 10.6 (range between 1-40) high-confidence genomic variants per genome. I still don't have validation data at hand so I can't guarantee the experimental validation rate, and as the AFs are higher we can't rule out CNVs. One tip is to calculate the average depth for each sample individually.

For the runtime, as the computation complexity is linearly correlated to the number of variants in your vcf, whether your vcf is generated from GATK HaplotypeCaller polidy 50, or MuTect2 single mode, what are your post filters will affect the performance. For an average of ~3500 variants per genome (30x), the average (draw 1 node 1 core CPU + predict 1 node 12 core 64g mem CPU) walltime: ~4hr usertime: ~20000s systime: ~5000s. Again as I said with different nodes the performance might vary a lot.

Hope the above info can help you.

Best,

Xiaoxu

**Comment by shishenyxx** [comment]
> Hi.
> 
> My main question is **"Is it recommended to run DeepMosaic to identify MVs in 30x data?"**
> 
> I am planning to pass thousands of human genome data (bam, vcf) to DeepMosaic, but their depth is 30x mostly. In the DeepMosaic paper, 30x results seem to be not okay from Extended Data Fig. 1. <img alt="image" width="687" src="https://user-images.githubusercontent.com/44763914/210918358-e03ca604-ef67-4b42-81d4-8927c9fde5ab.png">
> 
> And there is no data in the Main Figure 2 and Extended Data Figure 5. ![image](https://user-images.githubusercontent.com/44763914/210918707-4d955ea1-916b-4507-8cd6-266d8552b39e.png)
> 
> It looks okay in Extended Data Fig. 1 but I am not sure because I have no experience on it.
> 
> Can I use DeepMosaic for 30x data?
> 
> I also am wondering about the runtime (cpu time, wall time...)
> 
> Thanks, James

Hi James,

Sorry just saw that you edited your question. Compared with other methods we tried, I believe from our experience DeepMosaic is more suitable for mosaic variant calling in 30x WGS, especially if you don't have a matched control sample, as its training set already contains some 30x data. Although in general, it is challenging to detect mosaic variants from 30x WGS, we are testing some existing genomes in house: to make the long story short, if the genome quality is good, no contaminations, sequenced from DNA extracted from fresh frozen tissue, not FFPE, we get average 10.6 (range between 1-40) high-confidence genomic variants per genome. I still don't have validation data at hand so I can't guarantee the experimental validation rate, and as the AFs are higher we can't rule out CNVs (sensitivity even at high AF will drop to ~10%, which is expected for low AF). One tip is to calculate the average depth for each sample individually. So to answer your first question it depends on our expectations. If we expect 50% percent sensitivity it might be tough because of the limitation of the data. If I expect that there is at least something interesting that I can get from the data that are potential to be validated as positive, I will recommend it. 

For the runtime, as the computation complexity is linearly correlated to the number of variants in your vcf, whether your vcf is generated from GATK HaplotypeCaller polidy 50, or MuTect2 single mode, what are your post filters will affect the performance. For an average of ~3500 variants per genome (30x), the average (draw 1 node 1 core CPU + predict 1 node 12 core 64g mem CPU) walltime: ~4hr usertime: ~20000s systime: ~5000s. Again as I said with different nodes the performance might vary a lot.

Hope the above info can help you.

Best,

Xiaoxu

**Comment by changhan1110** [comment]
Hi Xiaoxu,

Thank you so much for the detailed replies! They are so helpful.
I thought DeepMosaic was the best option for my case but I wanted to make sure to get some comments from you.

Thanks again,
Changhan

**Comment by shishenyxx** [comment]
> Hi Xiaoxu,
> 
> Thank you so much for the detailed replies! They are so helpful. I thought DeepMosaic was the best option for my case but I wanted to make sure to get some comments from you.
> 
> Thanks again, Changhan

Hi Changhan,

Thank you for using DeepMosaic and hope it can help your research!

Best,

Xiaoxu
