### ISSUE TITLE
mac?

### ISSUE THREAD

**Issue by proukakis** [Virginiaxu/DeepMosaic#6]
hello we are hoping to start using this soon
we actually do a lot of our work on Macs, do you know if it will work?
(apologies if it is covered somewhere, i didn't spot it)

**Comment by shishenyxx** [comment]
Hi,

Thank you for your interest in DeepMosaic! We haven't tested it on Mac workstations so we cannot guarantee it will work. My personal feeling is it might work if your Mac is equipped with 2-3G free memory to load the reference genome and complete the visualization module, and some free CPU cores to run the classification module (you can't use the GPUs from your Mac because CUDA only supports NVIDIA GPUs). And of course with the storage spaces for the input, resource, and output files that are needed. Below are the estimated walltime and memory estimated from exomes and genomes. 
![image](https://user-images.githubusercontent.com/17311837/211534051-2312ad8d-d7e6-4005-9929-29b47c82d406.png)

Best,

Xiaoxu

**Comment by proukakis** [comment]
Thanks, we will try it for sure when my student finds some time

christos

From: Xiaoxu Yang ***@***.***>
Reply to: Virginiaxu/DeepMosaic ***@***.***>
Date: Tuesday, 10 January 2023 at 19:09
To: Virginiaxu/DeepMosaic ***@***.***>
Cc: "Proukakis, Christos" ***@***.***>, Author ***@***.***>
Subject: Re: [Virginiaxu/DeepMosaic] mac? (Issue #6)


⚠ Caution: External sender


Hi,

Thank you for your interest in DeepMosaic! We haven't tested it on Mac workstations so we cannot guarantee it will work. My personal feeling is it might work if your Mac is equipped with 2-3G free memory to load the reference genome and complete the visualization module, and some free CPU cores to run the classification module (you can't use the GPUs from your Mac because CUDA only supports NVIDIA GPUs). And of course with the storage spaces for the input, resource, and output files that are needed. Below are the estimated walltime and memory estimated from exomes and genomes.
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F17311837%2F211534051-2312ad8d-d7e6-4005-9929-29b47c82d406.png&data=05%7C01%7Cc.proukakis%40ucl.ac.uk%7C3d79baece77f4553b42d08daf33e35c9%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C638089745763742646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mpA3d4p%2FfFk9OBcXMSiRKixRo8w1TLAQO0za34iidAo%3D&reserved=0>

Best,

Xiaoxu
